
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-soladmins-com-tls
  namespace: argocd
spec:
  secretName:  argo-soladmins-com-tls
  duration: 2160h #90day
  renewBefore: 360h #before 15day
  issuerRef:
    name: my-issuer
    kind: ClusterIssuer
  commonName:  argo.soladmins.com
  dnsNames:
  -  argo.soladmins.com